### PR TITLE
Update cycle.md to include a description about the N3C cohort definition.

### PR DESCRIPTION
**Pull request by stephanieshong**
Added a sub-section: N3C Overall Cohort Definition

### CODE REVIEW

**Review by stephanieshong — COMMENTED** [review]
Looks good to me.

**Comment by stephanieshong** [comment]
@bryanlaraway - could you review? and approve?

**Comment by wibeasley** [comment]
@stephanieshong.  Thanks for the material.  I'm [touching up some small things](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/pull/145/commits) (like cross-refs), then I'll merge the pull.  @bryanlaraway, feel free to make revisions after the current PR is done.

**Comment by stephanieshong** [comment]
Thank you @wibeasley !

**Comment by wibeasley** [comment]
@stephanieshong & @bryanlaraway, I touched it up.  Hopefully you like it better.  Tell me if you'd like to change anything (or add another PR).

**Comment by bryanlaraway** [comment]
@stephanieshong & @wibeasley A couple notes:

- First line "Each COVID-positive patient is matched to roughly control cohort patients." -> Should probably add a 1:2 after the word "roughly."
- Second line, might want to specify that these are non-positive _COVID_ lab tests.
- Might want to add a word like project to the sentence where it says "...the control cohort decision may be different for each research  _project_ and..."

**Pull request merged**
